YoungDotx3/Models/MessageWall/MessageModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using YoungDotx3.Domain.Hallelujah;

namespace YoungDotx3.Models.MessageWall
{
    public class MessageModels
    {
        public MessageModels(Message message)
        {
            this.Id = message.Id;
            this.Nickname = message.Nickname;
            this.Content = message.Content;
            this.CreateDate = message.CreateDate.AddHours(8).ToString(Domain.DateTimeFormat.DateWithHyphen);
            this.CreateTime = message.CreateDate.AddHours(8).ToString(Domain.DateTimeFormat.Time);
        }

        public string Id { get; set; }
        public string Nickname { get; set; }
        public string Content { get; set; }
        public string CreateDate { get; set; }
        public string CreateTime { get; set; }
        public int Sequence { get; set; }
    }
}

YoungDotx3/Controllers/MessageWallController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using YoungDotx3.Domain;
using YoungDotx3.Filters;
using YoungDotx3.Models.MessageWall;

namespace YoungDotx3.Controllers
{
    public class MessageWallController : Controller
    {
        // GET: MessageWall
        public ActionResult Index()
        {
            //Service.MessageWallService service = new Service.MessageWallService();
            //var messages = service.GetMessages();
            //List<MessageModels> messageModelses = new List<MessageModels>();
            //messageModelses.AddRange(messages.Select(val => new MessageModels(val)));
            //return View(messageModelses);
            return View();
        }

        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post)]
        [AjaxValidateAntiForgeryToken]
        public ActionResult GetMessages(int page)
        {
            Service.MessageWallService service = new Service.MessageWallService();
            var messages = service.GetMessages(page);
            List<MessageModels> messageModelses = new List<MessageModels>();
            messageModelses.AddRange(messages.Messages.Select(val => new MessageModels(val)));

            return Content(JsonConvert.SerializeObject(new { messageModels = messageModelses }), "application/json");
        }

        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post)]
        [AjaxValidateAntiForgeryToken]
        public ActionResult Create(string nickname, string content)
        {
            var message = new Domain.MessageWall.Message
            {
                Nickname = nickname,
                Content = content,
                CreateDateTime = DateTime.Now
            };

            Service.MessageWallService service = new Service.MessageWallService();
            bool result = service.CreateMessage(message);

            return Content(JsonConvert.SerializeObject(new { isSuccess = result, messageModel = new MessageModels(message) }), "application/json");
        }
    }
}

YoungDotx3/Views/MessageWall/Index.cshtml
@using System.IdentityModel.Tokens
@model List<YoungDotx3.Models.MessageWall.MessageModels>

@{
    ViewBag.Title = "哈雷路亞";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    html, body {
        background-color: #e9ebee;
    }
    h3 {
        font-weight: bold;
    }
    .panel-content {
        margin: 20px;
    }
    .fullname {
        font-weight: bold;
        color: #292f33;
    }
    .btn-send, .btn-cancel {
        margin-left: 15px;
    }

    /*------------------- timeline ----------------------*/

    .timeline {
        position: relative;
        margin: 0 0 30px;
        padding: 0;
        list-style: none;
    }
    .timeline:before {
        content: '';
        position: absolute;
        top: 0;
        bottom: 0;
        width: 4px;
        background: #D8CEF6;
        left: 31px;
        margin: 0;
        border-radius: 2px;
    }
    .timeline>li {
        position: relative;
        margin-right: 10px;
        margin-bottom: 15px;
    }
    .timeline>li:after {
        clear: both;
    }
    .timeline>li:after, .timeline>li:before {
        content: " ";
        display: table;
        box-sizing: border-box;
    }
    .timeline>li>.fa, .timeline>li>.glyphicon, .timeline>li>.ion {
        height: 30px;
        font-size: 15px;
        line-height: 30px;
        position: absolute;
        border-radius: 50%;
        text-align: center;
        left: 18px;
        top: 0;
    }
    .tag.is-now {
        background-color: #ffc107;
        color: #fff;
    }
    .tag.is-danger {
        background-color: #ff3860;
        color: #fff;
    }
    .tag.is-primary {
        background-color: #00d1b2;
        color: #fff;
    }
    .tag.is-info {
        background-color: #3273dc;
        color: #fff;
    }
    .number, .tag {
        background-color: #f5f5f5;
        border-radius: 290486px;
        vertical-align: top;
    }
    .tag {
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        color: #4a4a4a;
        display: -webkit-inline-box;
        display: -ms-inline-flexbox;
        display: inline-flex;
        font-size: 12px;
        height: 24px;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        line-height: 16px;
        padding-left: 10px;
        padding-right: 10px;
    }
    .timeline>li>.timeline-item {
        box-shadow: 0 1px 1px rgba(0,0,0,.1);
        border-radius: 3px;
        margin-top: 0;
        background: #fff;
        color: #444;
        margin-left: 60px;
        margin-right: 15px;
        padding: 0;
        position: relative;
    }
    .timeline>li>.timeline-item>.time {
        color: #999;
        float: right;
        padding: 10px;
        font-size: 12px;
    }
    .timeline>li>.timeline-item>.timeline-body, .timeline>li>.timeline-item>.timeline-footer {
        padding: 12px;
    }
    .timeline>li>.timeline-item>.timeline-header {
        margin: 0;
        color: #555;
        border-bottom: 1px solid #f4f4f4;
        padding: 12px;
        font-size: 16px;
        line-height: 1.1;
    }
</style>

<div class="container">
    <ul id="timeline" class="timeline" style="margin-top: 50px">
        <li class="time-label">
            <span class="fa fa-hourglass-start tag is-now"></span>
        </li>
        <li id="leave-message" class="">
            @*<span class="fa fa-envelope tag is-info"></span>*@
            <div class="timeline-item">
                <div id="app" class="timeline-header">
                    <input id="nickname" class="form-control text-nickname" type="text" placeholder="暱稱..  (限20字)" maxlength="20"/>
                </div>
                <div class="timeline-body">
                    <textarea id="content" class="form-control textarea-content" placeholder="留言..  (限500字)" maxlength="500" rows="5"></textarea>
                </div>
                <div class="timeline-footer">
                    <button type="button" id="btn-send" class="btn btn-default btn-primary btn-send">送出</button>
                    <button type="button" id="btn-cancel" class="btn btn-default btn-cancel">取消</button>
                </div>
            </div>
        </li>
        <li id="initial"><span class="fa fa-clock-o tag is-white"></span></li>
    </ul>
    <footer class="w3-center w3-opacity w3-hover-opacity-off">
        <p class="copyright">Copyright &copy; @DateTime.Now.Year Chris80072 All rights reserved</p>
    </footer>
</div>

<div id="modal-alert" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content modal-alert">
            <div class="modal-body">
                <label id="alert-message"></label>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


@section scripts{
<script type="text/javascript">

    $(document).ready(function () {

        var date = '';
        var lastId = 0;
        var page = 1;
        var isQuerying = false;
        getMessages();

        $(window).scroll(function () {
            if (!isQuerying && lastId > 1) {
                //最後一頁scrollTop=body-window，300是預留空間
                var last = $("body").height() - $(window).height() - 300;
                if ($(window).scrollTop() >= last) {
                    getMessages();
                    isQuerying = true;
                }
            }
        });

        function getMessages() {
            $.ajax({
                type: "POST",
                url: "@Url.Action("GetMessages", "MessageWall")",
                data: { "page": page },
                dataType: "json",
                headers: {
                    'RequestVerificationToken': '@CommonRazorFunctions.GetAntiForgeryToken()'
                },
                success: function(result) {
                    if (checkTimeout(result)) {
                        page++;
                        var models = result.messageModels;
                        for (var i = 0; i < models.length > 0; i++) {
                            $('#initial').before(bindMessageHtml(models[i]));
                        }
                    } else {
                        alertMessage('伺服器忙碌中，請稍後再試！', 'danger');
                    }
                },
                error: function() {
                    alertMessage('伺服器忙碌中，請稍後再試！', 'danger');
                },
                complete: function () {
                    isQuerying = false;
                }
            });
        }

        function createMessage() {
            $.ajax({
                type: "POST",
                url: "@Url.Action("Create", "MessageWall")",
                data: { "nickname": $('#nickname').val(), "content": $('#content').val() },
                dataType: "json",
                headers: {
                    'RequestVerificationToken': '@CommonRazorFunctions.GetAntiForgeryToken()'
                },
                success: function(result) {
                    if (checkTimeout(result)) {

                        if (result.isSuccess) {
                            $('#content').val('');
                            var model = result.messageModel;
                            if ($('.' + model.CreateDate).length > 0) {
                                $('.' + model.CreateDate).after(bindMessageHtml(model));
                            } else {
                                $('#leave-message').after(bindMessageHtml(model));
                            }
                        } else {
                            alertMessage('新增失敗，請稍後再試！', 'danger');
                        }
                    }
                },
                error: function(result) {
                        alertMessage('伺服器忙碌中，請稍後再試！', 'danger');
                }
            });
        }

        function bindMessageHtml(messageModel) {
            lastId = messageModel.Id;
            var html = '';
            if (date != messageModel.CreateDate)
            {
                html += '   <li class="time-label ' + messageModel.CreateDate + '">';
                html += '       <span class="tag is-danger">' + messageModel.CreateDate + '</span>';
                html += '   </li>';
                date = messageModel.CreateDate;
            }

            html += '<li class="message">';
            html += getIconHtml(messageModel.Id);
            html += '   <div class="timeline-item">';
            html += '       <span class="time"><i class="fa fa-clock-o"></i>' + messageModel.CreateTime + '</span>';
            html += '       <h3 class="timeline-header">' + messageModel.Nickname + '</h3>';
            html += '       <div class="timeline-body">';
            html += getMessageHtml(messageModel.Content);
            html += '       </div>';
            html += '       <div class="timeline-footer"></div>';
            html += '   </div>';
            html += '</li>';

            return html;
        }

        function getIconHtml(seq) {
            var base = 3;
            if (seq % base === 0) {
                return '<span class="fa fa-envelope tag is-info"></span>';
            } else if (seq % base === 1) {
                return '<span class="fa fa-commenting-o tag is-danger"></span>';
            } else {
                return '<span class="fa fa-comments-o  tag is-primary"></span>';
            }
        }

        function getMessageHtml(content) {
            var result = '';
            var lines = content.split('\n');
            for (var i = 0; i < lines.length; i++) {
                result += '       <p>' + lines[i] + '</p>';
            }
            return result;
        }

        function alertMessage(message, type) {
            $('#alert-message').html(message);

            if (type === 'success')
                $('.modal-alert').css('background-color', '#dff0d8');
            else if (type === 'danger')
                $('.modal-alert').css('background-color', '#f2dede');
            else
                $('.modal-alert').css('background-color', '#ffffff');

            $('#modal-alert').modal('show');
            setTimeout(function () { $('#modal-alert').modal('hide'); }, 3000);
        }

        $('#btn-cancel').on('click', function() {
            $('#nickname, #content').val('');
        });

        $('#btn-send').on('click', function () {
            if ($('#nickname').val() === '') {
                alertMessage('請輸入暱稱！', 'danger');
                $('#nickname').trigger('focus');
            } else if ($('#content').val() === '') {
                alertMessage('請輸入內容！', 'danger');
                $('#content').trigger('focus');
            } else {
                createMessage();
            }
        });
    });
</script>
} 