YoungDotx3/Controllers/HallelujahController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using YoungDotx3.Domain;
using YoungDotx3.Filters;
using YoungDotx3.Models.MessageWall;
using YoungDotx3.Service;
using YoungDotx3.Domain.Hallelujah;

namespace YoungDotx3.Controllers
{
    public class HallelujahController : Controller
    {
        // GET: Hallelujah
        public ActionResult Index()
        {
            //Service.MessageWallService service = new Service.MessageWallService();
            //var messages = service.GetMessages();
            //List<MessageModels> messageModelses = new List<MessageModels>();
            //messageModelses.AddRange(messages.Select(val => new MessageModels(val)));
            //return View(messageModelses);
            return View();
        }

        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post)]
        [AjaxValidateAntiForgeryToken]
        public ActionResult GetMessages(string id)
        {
            HallelujahService service = new HallelujahService();
            var messages = service.GetMessages(id);
            List<MessageModels> messageModelses = new List<MessageModels>();
            messageModelses.AddRange(messages.Select(val => new MessageModels(val)));
            return Content(JsonConvert.SerializeObject(new { messages = messageModelses }), "application/json");
        }

        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post)]
        [AjaxValidateAntiForgeryToken]
        public ActionResult Create(string nickname, string content)
        {
            bool result = false;
            Message message = null;
            try
            {
                message = new Message
                {
                    Nickname = nickname,
                    Content = content,
                    CreateDate = DateTime.Now
                };

                HallelujahService service = new HallelujahService();
                service.CreateMessage(message);

                result = !string.IsNullOrEmpty(message.Id);
            }
            catch (Exception)
            {
            }

            return Content(JsonConvert.SerializeObject(new { isSuccess = result, messageModel = new MessageModels(message) }), "application/json");
        }
    }
}

YoungDotx3/Controllers/HappyBirthdayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using Newtonsoft.Json;
using YoungDotx3.Filters;
using YoungDotx3.Models.Calendar;

namespace YoungDotx3.Controllers
{

    
    public class HappyBirthdayController : Controller
    {
        public ActionResult Index()
        {
            Service.HappyBirthdayService service = new Service.HappyBirthdayService();
            MonthModels month = new MonthModels();
            //month.Today = DateTime.Now.ToString("yyyy-MM-dd");
            //var messages = service.GetMessagesByMonth();
            var messages = service.GetMessages();
            month.Messages.AddRange(messages.Select(val => new MessageModels(val)));
            return View(month);
        }

        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post)]
        [AjaxValidateAntiForgeryToken]
        public ActionResult Create(string nickname, string content, string color, string createDate)
        {
            bool result = false;

            try
            {
                if (Convert.ToDateTime(createDate) > DateTime.Now)
                {
                    var message = new Domain.HappyBirthday.Message
                    {
                        Nickname = nickname,
                        Content = content,
                        ColorCode = color,
                        Date = Convert.ToDateTime(createDate)
                    };

                    Service.HappyBirthdayService service = new Service.HappyBirthdayService();
                    service.CreateMessage(message);
                    result = !string.IsNullOrEmpty(message.Id);
                }
            }
            catch (Exception)
            {
            }

            return Content(JsonConvert.SerializeObject(new { Result = result }), "application/json");
        }
    }
}

YoungDotx3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh-Hant-TW">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 青春點點點</title>
    @Html.AntiForgeryToken()
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/reset.css" rel="stylesheet"/>
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<script src="~/Scripts/ga.js"></script>
<body>
    <nav id="nav-left" class="w3-sidenav sidenav hidden">
        <div class="w3-container sidenav-container">
            <a href="#" class="w3-hide-large w3-right w3-jumbo close-nav hide-nav" title="close menu">
                <i class="fa fa-remove"></i>
            </a>
        </div>
        <ul>
            <li class="li-link"><a href="@Url.Action("Index", "Home")" onclick="hideNav();"><i class="fa fa-home" aria-hidden="true"></i> 首頁</a></li>
            <li class="li-link"><a href="@Url.Action("Index", "HappyBirthday")" onclick="hideNav();"><i class="fa fa-birthday-cake" aria-hidden="true"></i> 生日快樂</a></li>
            <li class="li-link"><a href="@Url.Action("Index", "Hallelujah")" onclick="hideNav();"><i class="fa fa-child" aria-hidden="true"></i> 哈雷路亞</a></li>
            <li class="li-link"><a href="https://www.facebook.com/YoungDotx3/?fref=ts" target="_blank"><i class="fa fa-facebook-official"></i> 臉書粉絲團</a></li>
            <li class="li-link"><a href="http://youngdotsagit.blogspot.tw/" target="_blank"><i class="fa fa-music" aria-hidden="true"></i> 錄音檔</a></li>
            <li class="li-link"><a href="http://hichannel.hinet.net/radio/index.do?id=232" target="_blank"><i class="fa fa-podcast" aria-hidden="true"></i> 線上收聽: 飛碟電台</a></li>
            <li class="li-link"><a href="http://nbabull.wixsite.com/sponsor" target="_blank"><i class="fa fa-handshake-o" aria-hidden="true"></i> 支持我們</a></li>
            <li class="li-link"><a href="http://marcy.bigcartel.com/" target="_blank"><i class="fa fa-rocket" aria-hidden="true"></i> 限定商品</a></li>
        </ul>
    </nav>
    <div class="w3-overlay w3-hide-large w3-animate-opacity hide-nav" style="cursor: pointer" title="close side menu" id="myOverlay"></div>
    <span id="show-nav" class="w3-opennav w3-hide-large w3-xxlarge w3-hover-text-grey"><i class="fa fa-bars"></i></span>
    <div class="w3-main" style="margin-left: 250px">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/base")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/site.js"></script>
</body>
</html>